services:
  scstats:
    image: minat0/scstats:latest
    container_name: "SCStats"
    depends_on:
      - db
    env_file: '.env.prod'
    volumes:
      - scstats_data:/var/www/html
      - ./.env.prod:/var/www/html/.env
    networks:
      - scnetwork

  nginx:
    image: nginx:latest
    container_name: "SCStats-nginx"
    ports:
      - "8000:80"
    volumes:
      - scstats_data:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scstats
    networks:
      - scnetwork

  db:
    image: mysql:8.0
    container_name: "SCStats-db"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - scnetwork

networks:
  scnetwork:
    driver: bridge

volumes:
  scstats_data:
  mysql_data:
